### ISSUE TITLE
IllegalFlagValue in /certificate-transparency/python/ct/client/tools/print_log_list.py

### ISSUE THREAD

**Issue by seroscar2** [google/certificate-transparency#174]
If launch the tool "python print_log_list.py" I get the following error:

Traceback (most recent call last):
  File "print_log_list.py", line 155, in <module>
    sys.argv = FLAGS(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/gflags.py", line 1333, in __call__
    self._AssertAllValidators()
  File "/usr/local/lib/python2.7/dist-packages/gflags.py", line 1074, in _AssertAllValidators
    self._AssertValidators(all_validators)
  File "/usr/local/lib/python2.7/dist-packages/gflags.py", line 1093, in _AssertValidators
    raise IllegalFlagValue('%s: %s' % (message, str(e)))
gflags.IllegalFlagValue: flag --log_list=None: Flag --log_list must be specified.

I think I fulfill all requirements, according to "pip install -r requirements.txt" output. 
Thanks

**Comment by eranmes** [comment]
FYI that's how you'd run this command:
First, from www.certificate-transparency.org/known-logs, download log_list.json, log_list.sig, log_list_pubkey.pem and log_list_schema.json

Then:
python print_log_list.py --log_list=log_list.json --signature=log_list.sig --signer_key=log_list_pubkey.pem --log_list_schema=log_list_schema.json
