### ISSUE TITLE
Python monitor crash when logging.critical() called

### ISSUE THREAD

**Issue by phad** [google/certificate-transparency#575]
This backtrace was produced:

monitor.py:376 Fetched 1000 entries (total: 2335046 from 6802054)
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/grte/v4/k8-linux/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/grte/v4/k8-linux/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "google3/third_party/certificate_transparency/python/ct/client/reporter.py", line 138, in handle_writing
    logging.critical(ex_tb)
AttributeError: 'module' object has no attribute 'critical'

**Comment by phad** [comment]
Fixed by downgrading 'critical' to 'error' in commit 6ef16b68ea68d2c468c472b5902afb482124045b
