### ISSUE TITLE
ct-dns-server-test is failing

### ISSUE THREAD

**Issue by linshunghuang** [google/certificate-transparency#589]
Is this a known issue?
```
rm -rf /tmp/ct-test.$$ && mkdir /tmp/ct-test.$$ \
	&& python server/ct-dns-server-test.py /tmp/ct-test.$$ \
	&& rm -rf /tmp/ct-test.$$
I0318 19:05:06.292449 1906451200 cert_checker.cc:126] Added 1 new certificate(s) to trusted store
I0318 19:05:06.295019 1906451200 sqlite_db-inl.h:39] New SQLite database created in /tmp/ct-test.49185/ct-test-database.sqlite
I0318 19:05:06.298357 1906451200 log_lookup-inl.h:82] Found 0 new log entries
I0318 19:05:06.298377 1906451200 ct-server.cc:176] Tree successfully updated at Wed Mar 18 19:05:06 2015
I0318 19:05:06.298388 1906451200 ct-server.cc:236] Last tree update was at Wed Mar 18 19:05:06 2015
I0318 19:05:06.298400 1906451200 thread_pool.cc:91] ThreadPool starting with 8 threads
I0318 19:05:06.345126 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:06.381160 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:06.407068 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:06.443725 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:06.490098 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:06.521128 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:06.562829 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:06.595865 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:06.656327 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:06.694162 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:06.741107 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:06.797281 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:06.843842 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:06.900825 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:06.937844 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:06.995545 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:07.036834 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 243
I0318 19:05:07.070482 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:07.128331 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 242
I0318 19:05:07.178144 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 243
I0318 19:05:07.224859 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:07.266427 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:07.293972 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:07.314340 1906451200 log_lookup-inl.h:82] Found 23 new log entries
I0318 19:05:07.314357 1906451200 ct-server.cc:176] Tree successfully updated at Wed Mar 18 19:05:07 2015
I0318 19:05:07.329910 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:07.364506 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 243
I0318 19:05:07.422904 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 242
I0318 19:05:07.458937 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:07.494168 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:07.545861 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:07.580262 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 242
I0318 19:05:07.617733 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:07.648794 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:07.701761 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 242
I0318 19:05:07.735733 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 243
I0318 19:05:07.790305 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 242
I0318 19:05:07.827548 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:07.859349 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:07.883744 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:07.922051 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:07.962836 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:08.029249 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:08.053484 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:08.115835 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:08.197845 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:08.234935 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:08.268123 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:08.318104 1906451200 log_lookup-inl.h:82] Found 23 new log entries
I0318 19:05:08.318125 1906451200 ct-server.cc:176] Tree successfully updated at Wed Mar 18 19:05:08 2015
I0318 19:05:08.323184 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:08.405014 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:08.437662 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:08.471514 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:08.531970 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:08.582311 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 243
I0318 19:05:08.622475 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:08.668241 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:08.702656 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:08.750967 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:08.805151 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 244
I0318 19:05:08.871670 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:08.929499 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 243
I0318 19:05:08.966534 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:09.019583 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:09.057822 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:09.117542 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:09.166410 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:09.202483 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 244
I0318 19:05:09.231956 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:09.266757 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:09.320679 1906451200 log_lookup-inl.h:82] Found 21 new log entries
I0318 19:05:09.320701 1906451200 ct-server.cc:176] Tree successfully updated at Wed Mar 18 19:05:09 2015
I0318 19:05:09.331120 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 243
I0318 19:05:09.365723 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:09.409919 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:09.482537 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:09.534636 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:09.604713 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:09.656721 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:09.690300 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:09.733527 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:09.807605 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:09.840404 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:09.876664 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:09.910462 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:09.942963 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 242
I0318 19:05:09.978555 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:10.010355 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:10.060122 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 241
I0318 19:05:10.112665 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:10.155983 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:10.186990 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 243
I0318 19:05:10.221472 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:10.247645 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:10.324359 1906451200 log_lookup-inl.h:82] Found 22 new log entries
I0318 19:05:10.324381 1906451200 ct-server.cc:176] Tree successfully updated at Wed Mar 18 19:05:10 2015
I0318 19:05:10.327165 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:10.368263 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:10.403898 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 242
I0318 19:05:10.444457 33058816 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 239
I0318 19:05:10.499483 34668544 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:10.525679 35205120 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 242
I0318 19:05:10.568740 33595392 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:10.619988 32522240 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:10.657233 34131968 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 240
I0318 19:05:10.691570 31985664 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 237
I0318 19:05:10.741420 14372864 handler.cc:81] 127.0.0.1 "POST /ct/v1/add-chain" 200 238
I0318 19:05:11.334590 1906451200 log_lookup-inl.h:82] Found 11 new log entries
I0318 19:05:11.334617 1906451200 ct-server.cc:176] Tree successfully updated at Wed Mar 18 19:05:11 2015
I0318 19:05:12.392596 1906451200 log_lookup-inl.h:82] Found 0 new log entries
I0318 19:05:12.392638 1906451200 ct-server.cc:176] Tree successfully updated at Wed Mar 18 19:05:12 2015
F0318 19:05:12.761924 1906451200 event.cc:113] Check failed: r > 0 (-1 vs. 0) 
*** Check failure stack trace: ***
    @        0x107e8b448  google::LogMessage::Fail()
    @        0x107e8abf4  google::LogMessage::SendToLog()
    @        0x107e8b0a2  google::LogMessage::Flush()
    @        0x107e8e4ed  google::LogMessageFatal::~LogMessageFatal()
    @        0x107e8b753  google::LogMessageFatal::~LogMessageFatal()
    @        0x107db724c  EventLoop::OneLoop()
    @        0x107db7528  EventLoop::Forever()
    @        0x107db2e23  main
    @     0x7fff8a8bd5c9  start
    @                0x4  (unknown)
Traceback (most recent call last):
  File "server/ct-dns-server-test.py", line 345, in <module>
    sth = lookup.GetSTH()
  File "server/ct-dns-server-test.py", line 43, in GetSTH
    sth_str = self.GetOne('sth.example.com')
  File "server/ct-dns-server-test.py", line 36, in GetOne
    answers = self.Get(name)
  File "server/ct-dns-server-test.py", line 31, in Get
    answers = self.resolver.query(name, 'TXT')
  File "/Library/Python/2.7/site-packages/dns/resolver.py", line 901, in query
    timeout = self._compute_timeout(start)
  File "/Library/Python/2.7/site-packages/dns/resolver.py", line 739, in _compute_timeout
    raise Timeout
dns.exception.Timeout
make[1]: *** [test] Error 1
make: *** [cpp_test] Error 2
```

By the way I'm running on Mac.
```
$ brew list --versions
cmake 3.2.1
gflags 2.0
glog 0.3.3
json-c 0.12
ldns 1.6.17_1
libevent 2.0.22
openssl 1.0.2
pkg-config 0.28
protobuf 2.6.0
xz 5.2.1
```

**Comment by pphaneuf** [comment]
Maybe @benlaurie has an idea?
