### ISSUE TITLE
Are IndexErrors at ct/client/reporter.py", line 64, in _scan_der_cert expected?

### ISSUE THREAD

**Issue by linshunghuang** [google/certificate-transparency#769]
I ran python/utilities/logobserver/logobserver.py against https://ct.googleapis.com/testtube and noticed some IndexErrors during the run, for example:

```
ERROR:root:Traceback (most recent call last):
  File "/<MY_FOLDER>/ct/client/reporter.py", line 64, in _scan_der_cert
    root = cert.Certificate(der_chain[-1], strict_der=False)
IndexError: list index out of range

ERROR:root:list index out of range
ERROR:root:Entry 50614 in batch <50000, 50999> raised an exception during scan
```
The "extra_data" for log entries 50614 was "AAAA"

Nothing serious but just wondering, is throwing IndexError the desired behavior here? Thanks!

**Comment by phad** [comment]
There's two things here:
 1. the code is bugged because it doesn't make a check on the length of der_chain before trying to access it's end element -- that's easily fixed, and the result here would be that we don't create a root_issuer field in the  X509Description proto that's being built in _scan_der_cert

 2. this happened because, as you mention, that particular log entry didn't have an extra_data field.  Well, the 'AAAA' base64 value is \000\000\000 anyway.  My interpretation is that the log entry contains just an end-entity cert with no chain.  Perhaps it's self-signed?  Anyway this contravenes RFC6962 sect 3.1 https://tools.ietf.org/html/rfc6962#section-3.1 which states that 

"""Each submitted certificate MUST be accompanied by all
   additional certificates required to verify the certificate chain up
   to an accepted root certificate.  The root certificate itself MAY be
   omitted from the chain submitted to the log server."""

I'm not completely sure how TestTube is set up.  Possibly because it's for testing purposes it accepts all certs regardless of whether they have a chain leading to an accepted root.  @AlCutter do you know?

I don't think this bug would be hit if you ran the logobserver.py against one of the production CT Logs.
But it should still be fixed to not raise IndexException.

**Comment by benlaurie** [comment]
On 3 June 2015 at 12:16, Paul Hadfield <notifications@github.com> wrote:

> There's two things here:
>
>    1.
>
>    the code is bugged because it doesn't make a check on the length of
>    der_chain before trying to access it's end element -- that's easily fixed,
>    and the result here would be that we don't create a root_issuer field in
>    the X509Description proto that's being built in _scan_der_cert
>    2.
>
>    this happened because, as you mention, that particular log entry
>    didn't have an extra_data field. Well, the 'AAAA' base64 value is
>    \000\000\000 anyway. My interpretation is that the log entry contains just
>    an end-entity cert with no chain. Perhaps it's self-signed? Anyway this
>    contravenes RFC6962 sect 3.1
>    https://tools.ietf.org/html/rfc6962#section-3.1 which states that
>
> """Each submitted certificate MUST be accompanied by all
> additional certificates required to verify the certificate chain up
> to an accepted root certificate. The root certificate itself MAY be
> omitted from the chain submitted to the log server."""
>
> I'm not completely sure how TestTube is set up. Possibly because it's for
> testing purposes it accepts all certs regardless of whether they have a
> chain leading to an accepted root. @AlCutter <https://github.com/AlCutter>
> do you know?
>

Testtube only accepts certs chaining to roots it knows, like all logs. At
least, it should!

**Comment by eranmes** [comment]
It's entirely valid to have an empty extra_data field - in case a root is logged. That seems like the case you're hitting - the reporter should be changed not to assume the chain is non-empty (and probably use the leaf_cert as the root if it's empty).

**Comment by AlCutter** [comment]
That entry doesn't appear to be a self-signed root (although it is an intermediate), but it *is* issued directly by one of the certs in Testtube's set of trusted roots:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            18:40:33:5c:29:b0:7f:0d:1f:bf:ff:64:64:7e:38:f9
    Signature Algorithm: dsa_with_SHA256
        Issuer: C=US, O=Symantec Corporation, OU=Symantec Trust Network, OU=FOR TEST PURPOSES ONLY, CN=Symantec Class 3 TEST Public Primary Certification Authority-G7
        Validity
            Not Before: Dec  7 00:00:00 2012 GMT
            Not After : Dec  6 23:59:59 2022 GMT
        Subject: C=US, O=Symantec Corporation, OU=Symantec Trust Network, OU=FOR TEST PURPOSES ONLY, CN=Symantec Class 3 DSA EV SSL TEST CA
        Subject Public Key Info:
            Public Key Algorithm: dsaEncryption
                pub: 
                    00:9d:ca:97:4a:e2:a1:47:97:62:4e:a1:a0:bc:e8:
                    87:d4:ab:58:02:95:a3:09:eb:b6:15:f1:5e:8c:25:
                    d2:26:11:54:d7:d9:cc:1a:fb:41:23:0c:33:54:be:
                    9f:ae:d6:e4:8f:e4:51:c6:64:25:1a:9a:5e:f9:19:
                    ef:6b:34:19:64:0a:17:cc:9f:21:8b:0a:54:28:7e:
                    ff:05:00:69:01:85:88:0e:23:6b:2e:c7:8b:1b:61:
                    f5:89:0c:19:e1:d5:9a:98:b4:1e:46:05:8d:d6:42:
                    a4:d8:f4:96:ca:7d:49:33:8d:fc:e2:0d:b6:1f:1f:
                    a4:d1:6c:2a:b8:ab:e7:83:fd:ad:f2:2b:de:36:65:
                    40:2c:da:bc:3c:41:de:90:1f:2a:28:16:3d:29:3d:
                    69:5c:ae:b0:8a:2c:35:f7:51:a0:9d:4d:24:11:e0:
                    ac:48:99:10:5e:7d:fe:61:61:86:68:e9:c6:89:31:
                    f8:dd:bf:e4:18:b2:55:55:30:64:3b:f5:90:6a:1a:
                    3d:c8:0c:79:18:84:0a:2e:21:e6:fc:ed:5f:1e:e1:
                    67:f8:6d:3c:0c:11:6d:de:f6:fe:e5:31:4c:76:e5:
                    1b:68:46:8d:e1:bf:f0:95:af:23:22:d3:e0:a9:67:
                    4c:e1:05:4c:56:91:87:22:0f:98:c3:5a:0e:fc:9c:
                    d7:81
                P:   
                    00:ed:10:ce:4a:9e:3b:91:d1:8f:22:b5:33:76:88:
                    c6:c3:d2:9f:a0:98:a1:70:71:07:27:f5:3d:61:71:
                    39:52:2a:98:ae:27:72:37:bc:f0:bc:cb:3f:f9:95:
                    91:f2:0e:20:cb:ff:64:54:d1:44:33:0c:d7:c3:74:
                    df:d3:0e:b1:de:d0:0f:f3:21:18:37:c4:0c:87:d3:
                    02:9e:d9:98:ff:b3:b8:59:fc:d7:66:9e:ee:e4:26:
                    fc:aa:44:5c:ca:83:ac:91:de:59:7b:ac:77:d3:6e:
                    d6:ba:99:44:b7:6b:c3:e1:c9:39:00:0b:12:3c:d7:
                    9b:c6:e0:62:6b:4a:9e:0c:9f:82:88:87:73:14:6d:
                    cf:52:8e:9b:3e:99:2d:95:32:6a:a4:e3:2a:60:b5:
                    12:ea:65:98:99:7b:a0:78:da:ff:5e:bb:a9:d2:21:
                    63:23:56:46:3c:72:3e:a2:01:fc:8a:88:3e:c9:af:
                    74:04:a6:85:69:8c:98:74:e1:72:05:5d:60:df:06:
                    d2:2e:3e:5f:db:ee:08:0d:3e:07:1f:c8:7f:e3:64:
                    67:1b:c9:80:0f:d0:7b:8b:67:d0:66:e4:a1:f4:29:
                    34:21:41:a9:98:13:16:0d:87:84:9e:3c:18:84:87:
                    8f:49:6d:a8:b1:2c:b4:88:19:18:c5:91:ab:98:9c:
                    35:57
                Q:   
                    00:c5:25:3c:9c:a7:43:1a:50:e7:a0:54:35:c6:1b:
                    48:95:80:c5:2b:f3:d1:77:01:56:32:d0:18:ca:e7:
                    0a:07:c5
                G:   
                    4d:b1:a2:93:24:49:ed:b3:3a:82:33:cf:d4:e7:2d:
                    af:02:28:4c:cd:12:23:28:7e:21:94:82:0e:a7:3d:
                    f4:40:86:9d:63:19:f4:60:de:ba:c7:30:9f:eb:a5:
                    f4:f4:a6:85:6d:b9:9c:1e:da:b1:0f:b0:b7:af:0b:
                    57:ed:1d:60:36:17:a2:40:60:7c:83:0d:a6:cc:27:
                    31:d3:78:68:97:83:18:0e:36:fd:45:d5:f7:45:12:
                    fe:e1:2a:2f:30:7f:b1:73:7c:03:e3:e2:6b:00:15:
                    c3:e3:7a:83:d7:0b:28:5d:3e:7a:26:13:67:4e:d5:
                    cc:02:f7:8a:bc:ad:a1:72:c2:34:6c:84:a9:87:63:
                    b1:e2:db:3b:db:d1:47:f6:57:ba:22:22:04:ea:5b:
                    ca:67:c9:41:54:02:e3:82:05:04:cf:cc:fe:cc:26:
                    fd:20:a5:f3:c3:80:3c:89:5e:ad:31:67:2e:39:1b:
                    78:21:f7:e0:80:a6:d5:06:44:a8:2e:2c:a6:30:12:
                    4d:f3:02:40:53:5d:bc:81:04:84:21:d5:23:50:a9:
                    b7:04:b0:f4:1f:ef:dd:d3:5b:a3:d5:9b:73:48:09:
                    30:c3:34:7d:6f:ab:10:c2:67:b8:8c:71:16:2c:7e:
                    d8:ec:85:28:b7:c0:ad:65:eb:cf:9a:75:a3:ac:12:
                    3f
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            X509v3 Certificate Policies: 
                Policy: X509v3 Any Policy
                  CPS: http://www.symauth.com/cps/testca
                  User Notice:
                    Explicit Text: http://www.symauth.com/rpa

            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://pilot-crl.verisign.com/testpca3-g7.crl

            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Subject Alternative Name: 
                DirName:/CN=DSA2048,256-2
            X509v3 Subject Key Identifier: 
                F7:B1:41:29:F4:82:01:5C:0A:EA:8A:A7:75:79:26:C4:A7:98:BF:C3
            X509v3 Authority Key Identifier: 
                keyid:EE:37:0E:47:A1:B4:79:0F:8E:0C:C3:DA:47:A3:D1:5E:75:06:FF:B6

    Signature Algorithm: dsa_with_SHA256
         r:   
             00:82:60:b5:db:0f:8a:5e:77:f8:c1:c5:b0:a4:ca:
             8f:b6:3b:23:0f:74:2b:07:2d:64:56:0a:07:52:20:
             d4:f7:fd
         s:   
             6e:91:a3:6f:e6:9f:b5:0b:da:07:21:b1:a1:29:fb:
             47:45:41:6f:9d:bf:c2:b5:cf:b3:ac:cc:a4:76:cf:
             f1:fd
```

**Comment by linshunghuang** [comment]
This bug also occurred on entry 5301782 of the Google Aviator Log.

**Comment by linshunghuang** [comment]
This occurred when probing the other 2 Google production logs.

Also, the exception caused an entire batch of certs *not* being stored into CertDB. However, the "state" of the log was already updated as verified, so even if you re-run logobserver.py, you wouldn't re-insert the missing certs.

**Comment by eranmes** [comment]
Can you confirm this is with the latest version of the code? I thought I fixed a bug in that area.
If you could post the output of 'git log |head -5' and the command line you used to run the scan, I'll try and reproduced.

**Comment by linshunghuang** [comment]
Yeah I can reproduce this issue with the latest version.
```
linshung@linshung-mbp1 certificate-transparency$ git log |head -5
commit 81a74044f364a55609a54537d24b61fb363f7dcc
Merge: 3ad23bb 052341d
Author: Al Cutter <al-github@9600.org>
Date:   Tue Jul 21 16:33:51 2015 +0100

```
First, edit `python/ct/config/logs.config` to use Certly's log (since it's smaller than Google's).
```
ctlog:{
  log_server:'https://log.certly.io'
  log_id:'zbUXm3/BwEb+6jETaj+PAC5hgvr4iW/syLL1tatgSQA='
  public_key_info:{
    type:ECDSA
        pem_key:'-----BEGIN ECDSA PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0D'
        'AQcDQgAECyPLhWKYYUgEc+tUXfPQB4wtGS2MNvXrjwFCCnyYJifBtd2Sk7Cu+Js9DNhMTh'
        '35FftHaHu6ZrclnNBKwmbbSA==\n-----END ECDSA PUBLIC KEY-----'
  }
}
```
Must mkdir due to issue #771
```
linshung@linshung-mbp1 python$ mkdir /tmp/ct_monitor/
linshung@linshung-mbp1 python$ mkdir /tmp/ct_monitor/zbUXm3/
linshung@linshung-mbp1 python$ mkdir /tmp/ct_monitor/zbUXm3/BwEb+6jETaj+PAC5hgvr4iW/
```
Run logobserver.py
```
linshung@linshung-mbp1 certificate-transparency$ cd python/
linshung@linshung-mbp1 python$ python utilities/logobserver/logobserver.py
WARNING:root:Monitor state file not found, assuming first run.
ERROR:root:Traceback (most recent call last):
  File "/<MY_PATH>/certificate-transparency/python/ct/client/reporter.py", line 68, in _scan_der_cert
    root = cert.Certificate(der_chain[-1], strict_der=False)
IndexError: list index out of range

ERROR:root:list index out of range
ERROR:root:Entry 16640 in batch <16000, 16999> raised an exception during scan
```
Let's check the cert count in TempDB and CertDB
```
linshung@linshung-mbp1 tmp$ sqlite3 /tmp/ct_tmp/db1
SQLite version 3.8.5 2014-08-15 22:37:57
Enter ".help" for usage hints.
sqlite> select count(*) from entries;
18185
linshung@linshung-mbp1 tmp$ sqlite3 /tmp/ct_cert
SQLite version 3.8.5 2014-08-15 22:37:57
Enter ".help" for usage hints.
sqlite> select count(*) from certs;
17185
```
An entire batch of certs <16000, 16999> is missing.
