### ISSUE TITLE
python/ct/crypto/verify.py does not support RSA public keys

### ISSUE THREAD

**Issue by linshunghuang** [google/certificate-transparency#923]
Running python/utilities/logobserver/logobserver.py against https://ctlog.api.venafi.com fails with
```
ct.crypto.error.UnsupportedAlgorithmError: Key type 1 not supported
```
python/ct/config/logs.config:
```
ctlog:{
  log_server:'https://ctlog.api.venafi.com'
  log_id:'rDua7X+pZ0dXFZ5tfVdWcvnZgQCUHpve/+yhMTt1eC0='
  public_key_info:{
    type:RSA
    pem_key:'-----BEGIN RSA PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ'
    '8AMIIBCgKCAQEAolpIHxdSlTXLo1s6H1OCdpSj/4DyHDc8wLG9wVmLqy1lk9fz4ATVmm+/'
    '1iN2Nk8jmctUKK2MFUtlWXZBSpym97M7frGlSaQXUWyA3CqQUEuIJOmlEjKTBEiQAvpfDj'
    'CHjlV2Be4qTM6jamkJbiWtgnYPhJL6ONaGTiSPm7Byy57iaz/hbckldSOIoRhYBiMzeNoA'
    '0DiRZ9KmfSeXZ1rB8y8X5urSW+iBzf2SaOfzBvDpcoTuAaWx2DPazoOl28fP1hZ+kHUYvx'
    'bcMjttjauCFx+JII0dmuZNIwjfeG/GBb9frpSX219k1O4Wi6OEbHEr8at/XQ0y7gTikOxB'
    'n/s5wQIDAQAB\n-----END RSA PUBLIC KEY-----'
  }
}
```
Any plans to support it? Thanks!

**Comment by eranmes** [comment]
Not surprising -given that's the first log with RSA keys.

Could you paste a full stack-trace as well as the command-line you used for running the logobserver? Just so we can re-create.
Then I can have a look at the complexity of implementing support for RSA keys.
As you can see from https://github.com/google/certificate-transparency/blob/master/python/ct/crypto/verify.py#L39 ECDSA assumption is somewhat hard-coded.

**Comment by linshunghuang** [comment]
Sure. Using the modified `python/ct/config/logs.config` as pasted above, the command line is:
```
certificate-transparency$ cd python/
python$ export PYTHONPATH=${PYTHONPATH}:$(pwd)
python$ python utilities/logobserver/logobserver.py
Traceback (most recent call last):
  File "utilities/logobserver/logobserver.py", line 75, in <module>
    FLAGS.monitor_state_dir)
  File "/<MY_PATH>/certificate-transparency/python/ct/client/prober.py", line 44, in __init__
    merkle.MerkleVerifier(hasher))
  File "/<MY_PATH>/certificate-transparency/python/ct/crypto/verify.py", line 191, in __init__
    key_info.type)
ct.crypto.error.UnsupportedAlgorithmError: Key type 1 not supported
```

**Comment by RJPercival** [comment]
Support for RSA keys added.

**Comment by linshunghuang** [comment]
Thanks guys!
